### ISSUE TITLE
I think there is a bug in the implementation of bpc  

### ISSUE THREAD

**Issue by OleNet** [yzh119/BPT#2]
According to the material I have find from [here](https://www.padl.ws/papers/Paper%2026.pdf) and [here](https://stats.stackexchange.com/questions/211858/how-to-compute-bits-per-character-bpc), bpc=log2(NLL). 
But in the implementation in your [code](https://github.com/yzh119/BPT/blob/master/lm.py#L235), I found that bpc = NLL / log2. 
Is there something wrong for the calculation of bpc, or I have missed anything?

**Comment by yzh119** [comment]
My implementation follows the definition of BPC in https://arxiv.org/pdf/1308.0850.pdf (page 8) and aligns with the implementation with [Transformer-XL](https://github.com/kimiyoung/transformer-xl/blob/44781ed21dbaec88b280f74d9ae2877f52b492a5/pytorch/eval.py), and [adaptive-span transformer](https://github.com/facebookresearch/adaptive-span/blob/27b815fee821acce2c2d4104cc0720cb1dc74c37/main.py) and the StackOverflow thread you posted.

For the paper you mentioned, I think that's a typo in the paper. NLL has already applied a `log` to the input: https://pytorch.org/docs/stable/generated/torch.nn.NLLLoss.html#torch.nn.NLLLoss.

**Comment by OleNet** [comment]
OK， I got it , thanks
